### ISSUE TITLE
Use of undeclared type 'SwiftyAvatar' on @IBOutlet

### ISSUE THREAD

**Issue by kohdesmond** [dkalaitzidis/SwiftyAvatar#12]
```
import SwiftyAvatar

@IBOutlet var userimage: SwiftyAvatar!
```

how can i outlet the image if the photo will be downloaded from Web services.

Cheers

Desmond

**Comment by dkalaitzidis** [comment]
Hi, try something like that:

class ViewController: UIViewController {

    @IBOutlet weak var avatar: SwiftyAvatar?

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let catPictureURL = URL(string: "https://s3.amazonaws.com/37assets/svn/765-default-avatar.png")!
        let session = URLSession(configuration: .default)
        let downloadPicTask = session.dataTask(with: catPictureURL) { (data, response, error) in
            if let e = error {
                print("Error downloading cat picture: \(e)")
            } else {
                if let res = response as? HTTPURLResponse {
                    print("Downloaded cat picture with response code \(res.statusCode)")
                    if let imageData = data {
                        self.avatar?.image = UIImage(data: imageData)
                    } else {
                        print("Couldn't get image: Image is nil")
                    }
                } else {
                    print("Couldn't get response code for some reason")
                }
            }
        }
        
        downloadPicTask.resume()
    }

or use a library like Kingfisher to download and set the image. The above code works fine if you want to test it.

Thank you :)

**Comment by kohdesmond** [comment]
Thanks for the solution,

I'm getting this error and not sure why...

![screen shot 2017-05-19 at 09 34 37](https://cloud.githubusercontent.com/assets/1192544/26229731/67cd88a6-3c76-11e7-9900-8bc49f70f3a6.png)

**Comment by dkalaitzidis** [comment]
Hi, i'll look at it again after work today. 
Thanks.

**Comment by smarques84** [comment]
Same issue while compiling, have any idea whats going on?

**Comment by dkalaitzidis** [comment]
Until i submit a new update you can fix the problem by going to SwiftyAvatar.swift and make the class public. Also some other errors will occur but Xcode will give you the solution. After that you should have the following:

@IBDesignable public class SwiftyAvatar: UIImageView 
required public init?(coder aDecoder: 
override public func layoutSubviews()

**Comment by dkalaitzidis** [comment]
Use pod update to get the latest version (1.1.3). It's fixed there!
