### ISSUE TITLE
Readme Organization

### ISSUE THREAD

**Issue by lfarah** [dkalaitzidis/SwiftyAvatar#7]
Hey @dkalaitzidis, your library is really interesting.

The only problem I found was the `README.md`, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by dkalaitzidis** [comment]
Hi, I will try to do the read me today. I'll contact you again when it's finished. Thanks!

Στάλθηκε από το iPhone μου

11 Αυγ 2016, 04:40, ο/η Lucas Farah notifications@github.com έγραψε:
